### ISSUE TITLE
Strips flavor text from Recovery Checks

### ISSUE THREAD

**Issue by Mr-Monocyte** [illandril/FoundryVTT-chat-enhancements#6] opened 2021-02-12 09:12 UTC
Use of this module removes the text accompanying Recovery Check rolls made from the PF2e Character sheet. The test is what explains/interprets the results of the Recovery Check. Without the text, it just shows up as a 1d20 roll with no explanation.

**Comment by illandril** [comment] 2021-02-12 16:04
@Mr-Monocyte I cannot reproduce this with PF2e 1.11.4.3626 or 1.11.5.3707...
![Screenshot from 2021-02-12 10-49-35](https://user-images.githubusercontent.com/469205/107790573-ea2b0100-6d20-11eb-9461-0a4d3072228a.png)

Either this is something the PF2e system recently changed and you just need to update your system, you're using some other module or changed some setting that is changing things, or I'm not understanding what you mean by Recovery Check rolls (I don't play Pathfinder, so that is entirely possible).

If updating PF2e fixes this for you, let me know so I can close this issue.
If not, please let me know in more detail exactly what you're doing, what other modules you have enabled (including their versions), and what settings you have for those modules so I can reproduce this.

**Comment by illandril** [comment] 2021-02-12 16:11
Note: If PF2e did change how they handle Recovery Check chat messages, updating the system will only impact **new** chat messages, not old ones, so you'll need to roll a new Recovery Check to test that.

**Comment by illandril** [comment] 2021-02-27 02:31
I'm closing this under the assumption that this is not an issue with the latest PF2e. If this is not the case, I'll need details on how to reproduce the issue before I can do anything.

**Closed by illandril** 2021-02-27 02:31 UTC
Labels: compatibility issue
